image: python:3.8

stages:
- test
- release

before_script:
- pip install tox

python36:
  image: python:3.6
  stage: test
  script: tox -e py36

python37:
  image: python:3.7
  stage: test
  script: tox -e py37

python38:
  image: python:3.8
  stage: test
  script: tox -e py38

lint:
  stage: test
  script: tox -e lint

pypi:
    image: docker.km3net.de/base/python:3
    stage: release
    cache: {}
    script:
        - pip install twine wheel
        - python setup.py sdist bdist_wheel
        - twine upload dist/*
    only:
        - tags
