image: python:3.11-alpine

stages:
- test
- release

.python_coverage:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - coverage run
    - coverage report
    - coverage xml
  coverage: '/TOTAL.*?(\d+(?:\.\d+)\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

python37:
  extends: .python_coverage
  image: python:3.7-alpine
  before_script:
    - apk add gcc musl-dev
    - pip install -r requirements.txt

python38:
  extends: .python_coverage
  image: python:3.8-alpine

python39:
  extends: .python_coverage
  image: python:3.9-alpine

python310:
  extends: .python_coverage
  image: python:3.10-alpine

python311:
  extends: .python_coverage
  image: python:3.11-alpine

python312:
  extends: .python_coverage
  image: python:3.12-rc-alpine

lint:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script: black . --check && isort . --check-only

typing:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script: mypy .

pypi:
    image: docker.km3net.de/base/python:3
    stage: release
    cache: {}
    script:
        - pip install twine wheel
        - python setup.py sdist bdist_wheel
        - twine upload dist/*
    only:
        - tags
