image: python:3.8

stages:
- test

before_script:
- pip install tox

python37:
  image: python:3.7
  stage: test
  script: tox -e py37

python38:
  image: python:3.8
  stage: test
  script: tox -e py38

lint:
  stage: test
  script: tox -e lint
